version: '3'
services:
    db:
        container_name: database
        image: 'postgres:latest'
        restart: on-failure
        environment:
            - POSTGRES_PASSWORD=password
            - PGUSER=postgres
        volumes:
            - db:/var/lib/postgresql/data
    server:
        container_name: server
        build:
            context: ../../
            dockerfile: docker/development/Dockerfile.server
        image: minhsiung/devlinks.server.development
        ports:
            - '3000:3000'
        volumes:
            - ../../app/server:/app
            - node_modules_server:/app/node_modules
        depends_on:
            - db
    client:
        container_name: client
        build:
            context: ../../
            dockerfile: docker/development/Dockerfile.client
        image: minhsiung/devlinks.client.development
        depends_on:
            - server
        ports:
            - '3001:3001'
        volumes:
            - ../../app/client:/app
            - node_modules_client:/app/node_modules
volumes:
    db:
        driver: local
    node_modules_server:
    node_modules_client:
