FROM node:20 AS base

FROM base AS deps
WORKDIR /app
COPY ./app/client/package.json ./app/client/package-lock.json* ./app/client/
COPY ./package.json ./package-lock.json* ./
RUN npm ci

FROM base AS runner
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY ./app/client/ ./

ENV NODE_ENV=development

EXPOSE 3001

CMD npm run dev
