version: '3'
services:
  app:
    container_name: app
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    links:
      - db
  db:
    container_name: database
    image: "postgres:latest"
    restart: on-failure
    environment:
      - POSTGRES_PASSWORD=password
      - PGUSER=postgres
    volumes: 
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local
