// eslint-disable-next-line camelcase
import { Instrument_Sans } from 'next/font/google';
import ToastProvider from '@/components/toast';
import 'react-toastify/dist/ReactToastify.css';
import './globals.css';

const inter = Instrument_Sans({ subsets: ['latin'] });

export const metadata = {
	title: 'devlinks',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
	return (
		<html lang='en'>
			<body className={inter.className}>
				<ToastProvider>{children}</ToastProvider>
			</body>
		</html>
	);
}
