version: '3'

services:
    db:
        container_name: staging_database
        image: 'postgres:latest'
        restart: on-failure
        environment:
            - POSTGRES_PASSWORD=password
            - PGUSER=postgres
        volumes:
            - db:/var/lib/postgresql/data

    client:
        build:
            context: ../../
            dockerfile: docker/staging/Dockerfile.client
        image: minhsiung/devlinks.client.staging
        ports:
            - '3001:3001'
    server:
        build:
            context: ../../
            dockerfile: docker/staging/Dockerfile.server
        image: minhsiung/devlinks.server.staging
        ports:
            - '3000:3000'

volumes:
    db:
        driver: local
