FROM node:20 AS base


FROM base AS deps

# RUN apk add --no-cache libc6-compat

WORKDIR /app

COPY ./package.json ./package-lock.json ./
COPY ./app/server/package.json ./app/server/package-lock.json ./app/server/

RUN npm ci

FROM  base AS runner
WORKDIR /app

COPY --from=deps /app/node_modules ./node_modules
COPY ./app/server/ ./

RUN npx dotenvx run --env-file=.env.staging -- node ./bin/db/seed

CMD ["npm", "run", "staging"]


